name: Publish kubiya-workflow-sdk 📦 to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: write
      contents: write # IMPORTANT: mandatory for making GitHub Releases
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: UV build
        run: uv build

      - name: Publish package
        run: uv publish 